In [1]:
import pandas as pd

csv_path = r'C:\Users\Somi\Downloads\hypothyroid.csv'
df = pd.read_csv(csv_path)
df


age sex on_thyroxine query_on_thyroxine on_antithyroid_medication sick  \
0     41   F            f                  f                         f    f   
1     23   F            f                  f                         f    f   
2     46   M            f                  f                         f    f   
3     70   F            t                  f                         f    f   
4     70   F            f                  f                         f    f   
...   ..  ..          ...                ...                       ...  ...   
3767  30   F            f                  f                         f    f   
3768  68   F            f                  f                         f    f   
3769  74   F            f                  f                         f    f   
3770  72   M            f                  f                         f    f   
3771  64   F            f                  f                         f    f   

     pregnant thyroid_surgery I131_treatment query_hypothyroid  ...  \
0           f               f              f                 f  ...   
1           f               f              f                 f  ...   
2           f               f              f                 f  ...   
3           f               f              f                 f  ...   
4           f               f              f                 f  ...   
...       ...             ...            ...               ...  ...   
3767        f               f              f                 f  ...   
3768        f               f              f                 f  ...   
3769        f               f              f                 f  ...   
3770        f               f              f                 f  ...   
3771        f               f              f                 f  ...   

     T3_measured   T3 TT4_measured  TT4 T4U_measured   T4U FTI_measured  FTI  \
0              t  2.5            t  125            t  1.14            t  109   
1              t    2            t  102            f     ?            f    ?   
2              f    ?            t  109            t  0.91            t  120   
3              t  1.9            t  175            f     ?            f    ?   
4              t  1.2            t   61            t  0.87            t   70   
...          ...  ...          ...  ...          ...   ...          ...  ...   
3767           f    ?            f    ?            f     ?            f    ?   
3768           t  2.1            t  124            t  1.08            t  114   
3769           t  1.8            t  112            t  1.07            t  105   
3770           t    2            t   82            t  0.94            t   87   
3771           t  2.2            t   99            t  1.07            t   92   

     referral_source     Class  
0               SVHC  negative  
1              other  negative  
2              other  negative  
3              other  negative  
4                SVI  negative  
...              ...       ...  
3767           other  negative  
3768             SVI  negative  
3769           other  negative  
3770             SVI  negative  
3771           other  negative  

[3772 rows x 28 columns]

In [2]:
from sklearn.preprocessing import LabelEncoder
# Create a LabelEncoder object
label_encoder = LabelEncoder()

# Assuming your categorical column is 'gender' in your DataFrame
df['Class'] = label_encoder.fit_transform(df['Class'])
df['sex'] = label_encoder.fit_transform(df['sex'])
df['on_thyroxine'] = label_encoder.fit_transform(df['on_thyroxine'])
df['query_on_thyroxine'] = label_encoder.fit_transform(df['query_on_thyroxine'])
df['on_antithyroid_medication'] = label_encoder.fit_transform(df['on_antithyroid_medication'])
df['sick'] = label_encoder.fit_transform(df['sick'])
df['pregnant'] = label_encoder.fit_transform(df['pregnant'])
df['thyroid_surgery'] = label_encoder.fit_transform(df['thyroid_surgery'])
df['I131_treatment'] = label_encoder.fit_transform(df['I131_treatment'])
df['query_hypothyroid'] = label_encoder.fit_transform(df['query_hypothyroid'])
df['TT4_measured'] = label_encoder.fit_transform(df['TT4_measured'])
df['T4U_measured'] = label_encoder.fit_transform(df['T4U_measured'])
df['FTI_measured'] = label_encoder.fit_transform(df['FTI_measured'])

df['referral_source'] = label_encoder.fit_transform(df['referral_source'])

df['lithium'] = label_encoder.fit_transform(df['lithium'])
df['goitre'] = label_encoder.fit_transform(df['goitre'])
df['tumor'] = label_encoder.fit_transform(df['tumor'])
df['hypopituitary'] = label_encoder.fit_transform(df['hypopituitary'])
df['psych'] = label_encoder.fit_transform(df['psych'])
df['TSH_measured'] = label_encoder.fit_transform(df['TSH_measured'])
df['T3_measured'] = label_encoder.fit_transform(df['T3_measured'])
df['query_hyperthyroid'] = label_encoder.fit_transform(df['query_hyperthyroid'])

df

age  sex  on_thyroxine  query_on_thyroxine  on_antithyroid_medication  \
0     41    1             0                   0                          0   
1     23    1             0                   0                          0   
2     46    2             0                   0                          0   
3     70    1             1                   0                          0   
4     70    1             0                   0                          0   
...   ..  ...           ...                 ...                        ...   
3767  30    1             0                   0                          0   
3768  68    1             0                   0                          0   
3769  74    1             0                   0                          0   
3770  72    2             0                   0                          0   
3771  64    1             0                   0                          0   

      sick  pregnant  thyroid_surgery  I131_treatment  query_hypothyroid  ...  \
0        0         0                0               0                  0  ...   
1        0         0                0               0                  0  ...   
2        0         0                0               0                  0  ...   
3        0         0                0               0                  0  ...   
4        0         0                0               0                  0  ...   
...    ...       ...              ...             ...                ...  ...   
3767     0         0                0               0                  0  ...   
3768     0         0                0               0                  0  ...   
3769     0         0                0               0                  0  ...   
3770     0         0                0               0                  0  ...   
3771     0         0                0               0                  0  ...   

      T3_measured   T3  TT4_measured  TT4  T4U_measured   T4U  FTI_measured  \
0               1  2.5             1  125             1  1.14             1   
1               1    2             1  102             0     ?             0   
2               0    ?             1  109             1  0.91             1   
3               1  1.9             1  175             0     ?             0   
4               1  1.2             1   61             1  0.87             1   
...           ...  ...           ...  ...           ...   ...           ...   
3767            0    ?             0    ?             0     ?             0   
3768            1  2.1             1  124             1  1.08             1   
3769            1  1.8             1  112             1  1.07             1   
3770            1    2             1   82             1  0.94             1   
3771            1  2.2             1   99             1  1.07             1   

      FTI  referral_source Class  
0     109                1     1  
1       ?                4     1  
2     120                4     1  
3       ?                4     1  
4      70                3     1  
...   ...              ...   ...  
3767    ?                4     1  
3768  114                3     1  
3769  105                4     1  
3770   87                3     1  
3771   92                4     1  

[3772 rows x 28 columns]

In [3]:
from sklearn.impute import KNNImputer
import numpy as np 

df.replace("?", np.nan, inplace=True)
df = df.apply(pd.to_numeric, errors='coerce')

imputer = KNNImputer(n_neighbors=2)
df_imputed = imputer.fit_transform(df)
df = pd.DataFrame(df_imputed, columns=df.columns)
df

age  sex  on_thyroxine  query_on_thyroxine  on_antithyroid_medication  \
0     41.0  1.0           0.0                 0.0                        0.0   
1     23.0  1.0           0.0                 0.0                        0.0   
2     46.0  2.0           0.0                 0.0                        0.0   
3     70.0  1.0           1.0                 0.0                        0.0   
4     70.0  1.0           0.0                 0.0                        0.0   
...    ...  ...           ...                 ...                        ...   
3767  30.0  1.0           0.0                 0.0                        0.0   
3768  68.0  1.0           0.0                 0.0                        0.0   
3769  74.0  1.0           0.0                 0.0                        0.0   
3770  72.0  2.0           0.0                 0.0                        0.0   
3771  64.0  1.0           0.0                 0.0                        0.0   

      sick  pregnant  thyroid_surgery  I131_treatment  query_hypothyroid  ...  \
0      0.0       0.0              0.0             0.0                0.0  ...   
1      0.0       0.0              0.0             0.0                0.0  ...   
2      0.0       0.0              0.0             0.0                0.0  ...   
3      0.0       0.0              0.0             0.0                0.0  ...   
4      0.0       0.0              0.0             0.0                0.0  ...   
...    ...       ...              ...             ...                ...  ...   
3767   0.0       0.0              0.0             0.0                0.0  ...   
3768   0.0       0.0              0.0             0.0                0.0  ...   
3769   0.0       0.0              0.0             0.0                0.0  ...   
3770   0.0       0.0              0.0             0.0                0.0  ...   
3771   0.0       0.0              0.0             0.0                0.0  ...   

      T3_measured    T3  TT4_measured    TT4  T4U_measured    T4U  \
0             1.0  2.50           1.0  125.0           1.0  1.140   
1             1.0  2.00           1.0  102.0           0.0  0.950   
2             0.0  1.80           1.0  109.0           1.0  0.910   
3             1.0  1.90           1.0  175.0           0.0  1.075   
4             1.0  1.20           1.0   61.0           1.0  0.870   
...           ...   ...           ...    ...           ...    ...   
3767          0.0  2.05           0.0   93.5           0.0  0.870   
3768          1.0  2.10           1.0  124.0           1.0  1.080   
3769          1.0  1.80           1.0  112.0           1.0  1.070   
3770          1.0  2.00           1.0   82.0           1.0  0.940   
3771          1.0  2.20           1.0   99.0           1.0  1.070   

      FTI_measured    FTI  referral_source  Class  
0              1.0  109.0              1.0    1.0  
1              0.0  110.0              4.0    1.0  
2              1.0  120.0              4.0    1.0  
3              0.0  163.0              4.0    1.0  
4              1.0   70.0              3.0    1.0  
...            ...    ...              ...    ...  
3767           0.0  108.0              4.0    1.0  
3768           1.0  114.0              3.0    1.0  
3769           1.0  105.0              4.0    1.0  
3770           1.0   87.0              3.0    1.0  
3771           1.0   92.0              4.0    1.0  

[3772 rows x 28 columns]

In [4]:
y = df['Class']

x = df.drop('Class',axis=1)

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=100)


In [5]:
import joblib
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

# Create a Random Forest classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model on the training set
rf_classifier.fit(x_train, y_train)

# Make predictions on the testing set
y_pred = rf_classifier.predict(x_test)

# Save the trained model to a .pkl file using joblib
joblib.dump(rf_classifier, 'random_forest_model.pkl')

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Print the results
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_rep)


Accuracy: 0.9960
Precision: 0.9960
Recall: 0.9960
F1 Score: 0.9960

Confusion Matrix:
[[ 38   1   1]
 [  1 686   0]
 [  0   0  28]]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.97      0.95      0.96        40
         1.0       1.00      1.00      1.00       687
         2.0       0.97      1.00      0.98        28

    accuracy                           1.00       755
   macro avg       0.98      0.98      0.98       755
weighted avg       1.00      1.00      1.00       755



In [ ]:
df.to_csv('thybin.csv', index=False)